# Generated by Django 3.2.23 on 2023-12-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="이메일")),
                ("password", models.CharField(max_length=64, verbose_name="비밀번호")),
                (
                    "registered_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일자"),
                ),
            ],
            options={
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자",
                "db_table": "user",
            },
        ),
    ]
