# Generated by Django 3.2.23 on 2023-12-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "사용자", "verbose_name_plural": "사용자"},
        ),
        migrations.AddField(
            model_name="user",
            name="useremail",
            field=models.EmailField(default=1, max_length=128, verbose_name="사용자이메일"),
            preserve_default=False,
        ),
    ]
