# Generated by Django 3.2.23 on 2023-12-14 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="stuck",
            new_name="stock",
        ),
    ]
